# 두 개 다 설치되어 있어야 작동함
# sudo apt-get update
# sudo apt-get install -y docker-compose
# 또한, 보안그룹에 사용자 지정 TCP로 9092 포트를 허용해야 함

version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 43.201.3.45
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://43.201.3.45:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
