version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: market_follower
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
