-- member 테이블 생성
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    phone_number VARCHAR(255),
    birthday DATE,
    created_at TIMESTAMP,
    last_login_at TIMESTAMP
);

-- auth 테이블 생성
CREATE TABLE auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT fk_auth_member FOREIGN KEY (member_id) REFERENCES member(id)
);

-- 거래 가능 코인 테이블 생성
CREATE TABLE tradable_coin (
    market VARCHAR(20) PRIMARY KEY,
    korean_name VARCHAR(50),
    english_name VARCHAR(50),
    is_warning BOOLEAN,
    is_caution_price_fluctuations BOOLEAN,
    is_caution_trading_volume_soaring BOOLEAN,
    is_caution_deposit_amount_soaring BOOLEAN,
    is_caution_global_price_differences BOOLEAN,
    is_caution_concentration_of_small_accounts BOOLEAN,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
